### ISSUE TITLE
rvm, ruby 2.2

### ISSUE THREAD

**Issue by theB264** [PurityControl/osra-scripts#19]
Do you think we should include updating rvm in the ubuntu scripts?

`gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`
`rvm get stable`

**Comment by PurityControl** [comment]
We don't update rvm because its a provisioning script. But we do import the keys and install the latest version, followed by the version of ruby described in the rails Gemfile.
Or have I misunderstood?

**Comment by theB264** [comment]
No I probably misunderstood then
